local case = {}

function case.test_failure()
  error("Testing GitHub CI with failure")
end

return case
